# Generated by Django 6.1 on 2026-08-19 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("alert_id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("category", models.CharField()),
                ("severity", models.CharField()),
                ("state", models.CharField()),
                ("fingerprint", models.CharField()),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("cleared_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "server_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="servers.servers",
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="servers.service",
                    ),
                ),
            ],
        ),
    ]
