# Generated by Django 6.1 on 2026-08-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0001_initial"),
        ("ml_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="detection_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ml_model.anomalydetection",
            ),
        ),
    ]
