# Generated by Django 6.1.1 on 2026-09-03 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userpreference_default_environment_and_more'),
        ('alert', '0002_alert_detection_id'),
        ('ml_model', '0002_alter_anomalydetection_options_and_more'),
        ('servers', '0002_alter_metrics_options_alter_servers_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-triggered_at', 'alert_id']},
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='alert',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='fingerprint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='alert',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], db_index=True, default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['ACTIVE', 'ACKNOWLEDGED'])), fields=('organization', 'fingerprint'), name='unique_open_alert_fingerprint'),
        ),
    ]
