# Generated by Django 6.0.6 on 2026-08-17 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 8, 17, 22, 40, 15, 720401)
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 8, 17, 22, 40, 15, 720422)
            ),
        ),
    ]
