# Generated by Django 6.1 on 2026-08-17 16:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_users_created_at_alter_users_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 8, 17, 22, 55, 55, 849439)
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 8, 17, 22, 55, 55, 849492)
            ),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("preference_id", models.UUIDField(primary_key=True, serialize=False)),
                ("notifications_enabled", models.BooleanField(default=False)),
                ("refresh_interval_seconds", models.IntegerField(default=10)),
                ("timezone", models.CharField()),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=datetime.datetime(2026, 8, 17, 22, 55, 55, 852974)
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
