# Generated by Django 6.1 on 2026-09-01 06:09

import datetime
import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_users_options_users_is_email_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("summary", models.TextField()),
                ("logo_url", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2026, 9, 1, 12, 9, 29, 66572)
                    ),
                ),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "role",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("OWNER", "Owner of the organization"),
                            ("ADMIN", "Admins assigned by owners of the organization"),
                            (
                                "ENGINEER",
                                "Engineers assigned by owners or admins of the organization",
                            ),
                        ],
                        default="ENGINEER",
                        max_length=8,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2026, 9, 1, 12, 9, 29, 78539)
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role__in", ["OWNER", "ADMIN", "ENGINEER"])
                        ),
                        name="accounts_OrganizationMembership_role_RoleEnum",
                    )
                ],
            },
        ),
    ]
