# Generated by Django 6.1.1 on 2026-09-02 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_organizationmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 2, 18, 12, 1, 541176)),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 2, 18, 12, 1, 554075)),
        ),
    ]
