# Generated by Django 6.1.1 on 2026-09-02 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_organization_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 2, 18, 14, 33, 792899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 2, 18, 14, 33, 812528, tzinfo=datetime.timezone.utc)),
        ),
    ]
