# Generated by Django 6.1.1 on 2026-09-02 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_organization_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
