# Generated by Django 6.1.1 on 2026-09-03 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_allow_multiple_owned_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='default_environment',
            field=models.CharField(default='production', max_length=64),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(default='dark', max_length=16),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preference_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
