# Generated by Django 6.0.6 on 2026-09-07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0014_monitoring_tenant_and_installer_stage"),
        ("servers", "0008_serviceadminassignmentevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(db_index=True, help_text="When the request was received by the origin server.")),
                ("source_ip", models.GenericIPAddressField(db_index=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=2048)),
                ("query_string", models.CharField(blank=True, default="", max_length=4096)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=2048)),
                ("content_length", models.IntegerField(blank=True, null=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("referer", models.CharField(blank=True, default="", max_length=2048)),
                ("protocol", models.CharField(blank=True, default="", help_text='e.g. "HTTP/1.1"', max_length=20)),
                ("headers_digest", models.JSONField(blank=True, default=dict, help_text="Sanitised header summary (no auth tokens or cookies).")),
                ("source", models.CharField(choices=[("EXTERNAL", "Monitored server (Alloy agent)"), ("PLATFORM", "Infra-Monitor API itself")], db_index=True, default="EXTERNAL", max_length=10)),
                ("zone", models.CharField(choices=[("GREEN", "Safe"), ("GRAY", "Suspicious"), ("RED", "Malicious"), ("UNCLASSIFIED", "Pending classification")], db_index=True, default="UNCLASSIFIED", max_length=14)),
                ("confidence", models.FloatField(blank=True, help_text="0.0 – 1.0 classifier confidence.", null=True)),
                ("threat_signals", models.JSONField(blank=True, default=list, help_text='List of threat signal codes, e.g. ["sql_injection", "path_traversal"].')),
                ("classified_at", models.DateTimeField(blank=True, null=True)),
                ("classified_by", models.CharField(choices=[("ML_MODEL", "ML model (Random Forest / XGBoost)"), ("GEMINI", "Gemini LLM escalation"), ("RULE", "Deterministic rule engine"), ("UNCLASSIFIED", "Not yet classified")], default="UNCLASSIFIED", max_length=14)),
                ("feature_vector", models.JSONField(blank=True, help_text="Extracted numeric feature vector sent to the ML model.", null=True)),
                ("admin_verdict", models.CharField(blank=True, help_text='"confirmed_safe" or "confirmed_threat"', max_length=20, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="request_logs", to="accounts.organization")),
                ("server", models.ForeignKey(blank=True, help_text="Null for PLATFORM-source requests.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="request_logs", to="servers.servers")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_request_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["organization", "zone", "-timestamp"], name="sanitize_re_organiz_6a4c84_idx"),
                    models.Index(fields=["organization", "source_ip", "-timestamp"], name="sanitize_re_organiz_8c9003_idx"),
                    models.Index(fields=["organization", "source", "-timestamp"], name="sanitize_re_organiz_0d783e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShieldConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("enabled", models.BooleanField(default=True, help_text="Master switch: when off, incoming request logs are stored but not classified.")),
                ("gemini_escalation", models.BooleanField(default=True, help_text="Send GRAY-zone requests to Gemini for deeper analysis.")),
                ("platform_self_monitor", models.BooleanField(default=True, help_text="Also classify requests arriving at the Infra-Monitor platform API.")),
                ("red_suggestion_threshold", models.IntegerField(default=5, help_text="Number of RED requests from an IP before generating a threat suggestion.")),
                ("gray_suggestion_threshold", models.IntegerField(default=20, help_text="Number of GRAY requests from an IP before generating a threat suggestion.")),
                ("suggestion_window_minutes", models.IntegerField(default=60, help_text="Rolling window (in minutes) for counting per-IP zone hits.")),
                ("notify_on_red", models.BooleanField(default=True, help_text="Send an in-app notification when a threat suggestion is created.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="shield_config", to="accounts.organization")),
            ],
            options={"verbose_name": "Shield Configuration", "verbose_name_plural": "Shield Configurations"},
        ),
        migrations.CreateModel(
            name="ThreatSuggestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("trigger_zone", models.CharField(choices=[("RED", "Triggered by RED-zone threshold"), ("GRAY", "Triggered by GRAY-zone threshold")], max_length=4)),
                ("request_count", models.IntegerField(help_text="Number of zone-matching requests from this IP in the window.")),
                ("window_start", models.DateTimeField(help_text="Start of the rolling window that triggered the suggestion.")),
                ("window_end", models.DateTimeField(help_text="End of the rolling window that triggered the suggestion.")),
                ("sample_paths", models.JSONField(blank=True, default=list, help_text="Up to 10 example request paths that contributed to this suggestion.")),
                ("top_threat_signals", models.JSONField(blank=True, default=list, help_text="Most frequent threat signal codes from the requests.")),
                ("gemini_analysis", models.TextField(blank=True, default="", help_text="Gemini's reasoning if escalation was used.")),
                ("status", models.CharField(choices=[("PENDING", "Awaiting admin review"), ("ACCEPTED", "Admin acknowledged as threat"), ("DISMISSED", "Admin dismissed as safe")], db_index=True, default="PENDING", max_length=10)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, default="", help_text="Free-text notes the admin can attach when accepting or dismissing.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="threat_suggestions", to="accounts.organization")),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_threat_suggestions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "status", "-created_at"], name="sanitize_th_organiz_13d72a_idx"),
                    models.Index(fields=["organization", "ip_address", "-created_at"], name="sanitize_th_organiz_93fc14_idx"),
                ],
            },
        ),
    ]
