# Generated by Django 6.1 on 2026-08-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                ("log_id", models.UUIDField(primary_key=True, serialize=False)),
                ("source", models.CharField()),
                ("log_level", models.CharField()),
                ("message", models.TextField()),
                ("metadata", models.JSONField()),
                ("logged_at", models.DateTimeField()),
                ("ingested_at", models.DateTimeField()),
            ],
        ),
    ]
