# Generated by Django 6.1 on 2026-08-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="server_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="servers.servers",
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="service_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="servers.service",
            ),
        ),
    ]
