# Generated by Django 6.1.1 on 2026-09-03 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userpreference_default_environment_and_more'),
        ('log', '0002_logentry_server_id_logentry_service_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-logged_at', 'log_id']},
        ),
        migrations.AddField(
            model_name='logentry',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='ingested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_level',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='logged_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
