# Generated by Django 6.1.1 on 2026-09-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userpreference_default_environment_and_more'),
        ('log', '0003_alter_logentry_options_logentry_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.organization'),
        ),
    ]
