"""
Django settings for infra_monitor project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-rp7i42w5po0vhxn!zn0jcz#8_o*_6*rt31*^(@#tq!$h6o$!h(",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
USE_X_FORWARDED_HOST = os.getenv("USE_X_FORWARDED_HOST", "False").lower() in ("true", "1", "yes")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if origin
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    # Local apps
    "accounts",
    "ai",
    "incident",
    "log",
    "servers",
    "alert",
    "ml_model",
    "installer",
    "dashboard",
]


# AUTH USER MODEL
AUTH_USER_MODEL = "accounts.Users"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "infra_monitor.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "infra_monitor.wsgi.application"
ASGI_APPLICATION = "infra_monitor.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("DB_NAME", os.getenv("POSTGRES_DB", "ai-infra-monitor")),
        "USER": os.getenv("DB_USER", os.getenv("POSTGRES_USER", "monitor")),
        "PASSWORD": os.getenv("DB_PASSWORD", os.getenv("POSTGRES_PASSWORD", "monitor")),
        "HOST": os.getenv("DB_HOST", "postgres"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        "CONN_HEALTH_CHECKS": True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ─────────────────────────────────────────────────────────────────
# Django REST Framework
# ─────────────────────────────────────────────────────────────────

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_THROTTLE_RATES": {
        "organization_search": "60/minute",
        "membership_request": "10/hour",
        "assistant_ticket": "30/minute",
    },
}

# ─────────────────────────────────────────────────────────────────
# Simple JWT
# ─────────────────────────────────────────────────────────────────

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", "30"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# ─────────────────────────────────────────────────────────────────
# CORS
# ─────────────────────────────────────────────────────────────────

CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000",
).split(",")

CORS_ALLOW_CREDENTIALS = True

# ─────────────────────────────────────────────────────────────────
# Google OAuth 2.0 SMTP Configuration
# ─────────────────────────────────────────────────────────────────

GMAIL_SENDER_EMAIL = os.getenv("GMAIL_SENDER_EMAIL", "")
GMAIL_CLIENT_ID = os.getenv("GMAIL_CLIENT_ID", "")
GMAIL_CLIENT_SECRET = os.getenv("GMAIL_CLIENT_SECRET", "")
GMAIL_REFRESH_TOKEN = os.getenv("GMAIL_REFRESH_TOKEN", "")

# ─────────────────────────────────────────────────────────────────
# OTP Configuration
# ─────────────────────────────────────────────────────────────────

OTP_EXPIRY_MINUTES = int(os.getenv("OTP_EXPIRY_MINUTES", "10"))
MONITORING_ENROLLMENT_EXPIRY_MINUTES = int(os.getenv("MONITORING_ENROLLMENT_EXPIRY_MINUTES", "15"))
MONITORING_INSTALL_URL = os.getenv(
    "MONITORING_INSTALL_URL",
    "https://monitor.example/api/monitoring/install.sh",
)
MONITORING_PUBLIC_BASE_URL = os.getenv("MONITORING_PUBLIC_BASE_URL", "")
MONITORING_SERVER_URL = os.getenv("MONITORING_SERVER_URL", MONITORING_PUBLIC_BASE_URL)
MONITORING_CREDENTIAL_OVERLAP_MINUTES = int(
    os.getenv("MONITORING_CREDENTIAL_OVERLAP_MINUTES", "15")
)
MONITORING_REMOTE_WRITE_MAX_COMPRESSED_BYTES = int(
    os.getenv("MONITORING_REMOTE_WRITE_MAX_COMPRESSED_BYTES", str(10 * 1024 * 1024))
)
MONITORING_REMOTE_WRITE_MAX_DECOMPRESSED_BYTES = int(
    os.getenv("MONITORING_REMOTE_WRITE_MAX_DECOMPRESSED_BYTES", str(100 * 1024 * 1024))
)
# Django otherwise rejects request.body at its smaller global default before the
# metrics view can return the intended 413 response at the configured limit.
DATA_UPLOAD_MAX_MEMORY_SIZE = MONITORING_REMOTE_WRITE_MAX_COMPRESSED_BYTES
VICTORIAMETRICS_INSERT_URL = os.getenv("VICTORIAMETRICS_INSERT_URL", "http://vminsert:8480")
VICTORIAMETRICS_WRITE_TIMEOUT_SECONDS = float(
    os.getenv("VICTORIAMETRICS_WRITE_TIMEOUT_SECONDS", "10")
)
VICTORIAMETRICS_SELECT_URL = os.getenv("VICTORIAMETRICS_SELECT_URL", "http://vmselect:8481")
VICTORIAMETRICS_QUERY_TIMEOUT_SECONDS = float(
    os.getenv("VICTORIAMETRICS_QUERY_TIMEOUT_SECONDS", "10")
)

ML_SERVICE_URL = os.getenv("ML_SERVICE_URL", "http://ml_service:80")
ML_SERVICE_TOKEN = os.getenv("ML_SERVICE_TOKEN", "")
ML_REQUEST_TIMEOUT_SECONDS = float(os.getenv("ML_REQUEST_TIMEOUT_SECONDS", "30"))
ML_TRAINING_LOOKBACK_HOURS = int(os.getenv("ML_TRAINING_LOOKBACK_HOURS", "24"))
ML_INFERENCE_WINDOW_SECONDS = int(os.getenv("ML_INFERENCE_WINDOW_SECONDS", "300"))
ML_METRIC_STEP_SECONDS = int(os.getenv("ML_METRIC_STEP_SECONDS", "60"))
ML_ORCHESTRATION_INTERVAL_SECONDS = int(os.getenv("ML_ORCHESTRATION_INTERVAL_SECONDS", "300"))

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-3.7-flash")
GEMINI_REQUEST_TIMEOUT_SECONDS = float(os.getenv("GEMINI_REQUEST_TIMEOUT_SECONDS", "60"))
ASSISTANT_WS_TICKET_TTL_SECONDS = int(
    os.getenv("ASSISTANT_WS_TICKET_TTL_SECONDS", "60")
)

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/1")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 55
CELERY_BEAT_SCHEDULE = {
    "evaluate-service-lifecycle": {
        "task": "servers.evaluate_service_lifecycle",
        "schedule": int(os.getenv("SERVICE_LIFECYCLE_INTERVAL_SECONDS", "30")),
    },
    "dispatch-service-ml": {
        "task": "ml_model.dispatch_service_ml",
        "schedule": ML_ORCHESTRATION_INTERVAL_SECONDS,
    },
}

SERVICE_STALE_AFTER_SECONDS = int(os.getenv("SERVICE_STALE_AFTER_SECONDS", "90"))
SERVICE_OFFLINE_AFTER_SECONDS = int(os.getenv("SERVICE_OFFLINE_AFTER_SECONDS", "300"))

# ─────────────────────────────────────────────────────────────────
# Frontend URLs
# ─────────────────────────────────────────────────────────────────

FRONTEND_WEB_URL = os.getenv("FRONTEND_WEB_URL", "http://localhost:3000")
