# Generated by Django 6.1 on 2026-08-19 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentAlert",
            fields=[
                (
                    "incident_alert_id",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("linked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "incident_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident.incident",
                    ),
                ),
            ],
        ),
    ]
