# Generated by Django 6.1 on 2026-08-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0002_alert_detection_id"),
        ("incident", "0002_incidentalert"),
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="server_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="servers.servers",
            ),
        ),
        migrations.AddField(
            model_name="incidentalert",
            name="alert_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="alert.alert"
            ),
        ),
    ]
