# Generated by Django 6.1.1 on 2026-09-03 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userpreference_default_environment_and_more'),
        ('alert', '0003_alter_alert_options_alert_acknowledged_by_and_more'),
        ('incident', '0003_incident_server_id_incidentalert_alert_id'),
        ('servers', '0002_alter_metrics_options_alter_servers_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-detected_at', 'incident_id']},
        ),
        migrations.AlterModelOptions(
            name='incidentupdate',
            options={'ordering': ['-created_at', 'update_id']},
        ),
        migrations.AddField(
            model_name='incident',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], db_index=True, default='NEW', max_length=16),
        ),
        migrations.AlterField(
            model_name='incidentalert',
            name='incident_alert_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='action',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='new_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='old_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='update_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(fields=('organization', 'incident_code'), name='unique_org_incident_code'),
        ),
        migrations.AddConstraint(
            model_name='incidentalert',
            constraint=models.UniqueConstraint(fields=('incident_id', 'alert_id'), name='unique_incident_alert'),
        ),
    ]
