# Generated by Django 6.1.1 on 2026-09-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userpreference_default_environment_and_more'),
        ('incident', '0004_alter_incident_options_alter_incidentupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='accounts.organization'),
        ),
    ]
