# Generated by Django 6.1 on 2026-08-19 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiAnalysis",
            fields=[
                ("analysis_id", models.UUIDField(primary_key=True, serialize=False)),
                ("summary", models.CharField()),
                ("explanation", models.CharField()),
                ("confidence_score", models.FloatField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                ("message_id", models.UUIDField(primary_key=True, serialize=False)),
                ("sender_type", models.CharField()),
                ("message", models.CharField()),
                ("evidence", models.JSONField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AiLogFinding",
            fields=[
                ("finding_id", models.UUIDField(primary_key=True, serialize=False)),
                ("relevance_score", models.FloatField()),
                ("explanation", models.CharField()),
                (
                    "analysis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ai.aianalysis"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AiRecommendation",
            fields=[
                (
                    "recommendation_id",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("action_text", models.CharField()),
                ("risk_level", models.IntegerField()),
                ("is_completed", models.BooleanField()),
                (
                    "analysis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ai.aianalysis"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AiRootCause",
            fields=[
                ("root_cause_id", models.UUIDField(primary_key=True, serialize=False)),
                ("cause_text", models.CharField()),
                ("confidence_score", models.FloatField()),
                ("rank_order", models.IntegerField()),
                (
                    "analysis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ai.aianalysis"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                (
                    "conversation_id",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
