# Generated by Django 6.1 on 2026-08-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("incident", "0002_incidentalert"),
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysis",
            name="incident_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incident.incident",
            ),
        ),
        migrations.AddField(
            model_name="ailogfinding",
            name="log_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="log.logentry",
            ),
        ),
        migrations.AddField(
            model_name="assistantconversation",
            name="incident_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incident.incident",
            ),
        ),
        migrations.AddField(
            model_name="assistantmessage",
            name="conversation_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai.assistantconversation",
            ),
        ),
    ]
