# Generated by Django 6.1 on 2026-08-19 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyDetection",
            fields=[
                ("detection_id", models.UUIDField(primary_key=True, serialize=False)),
                ("anomaly_score", models.FloatField()),
                ("confidence_score", models.FloatField()),
                ("is_anomaly", models.BooleanField()),
                ("feature_values", models.JSONField()),
                ("window_started_at", models.DateTimeField()),
                ("window_ended_at", models.DateTimeField()),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "server_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="servers.servers",
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="servers.service",
                    ),
                ),
            ],
        ),
    ]
