# Generated by Django 6.1.1 on 2026-09-03 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userpreference_default_environment_and_more'),
        ('ml_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalydetection',
            options={'ordering': ['-detected_at', 'detection_id']},
        ),
        migrations.AddField(
            model_name='anomalydetection',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detections', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='anomalydetection',
            name='detection_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anomalydetection',
            name='feature_values',
            field=models.JSONField(default=dict),
        ),
    ]
