# Generated by Django 6.1.1 on 2026-09-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userpreference_default_environment_and_more'),
        ('ml_model', '0002_alter_anomalydetection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalydetection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detections', to='accounts.organization'),
        ),
    ]
