# Generated by Django 6.1 on 2026-08-19 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Servers",
            fields=[
                ("server_id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("host_name", models.CharField()),
                ("ip_address", models.CharField()),
                ("environment", models.CharField()),
                ("os_type", models.CharField()),
                ("status", models.CharField()),
                ("agent_config", models.JSONField()),
                ("last_seen_at", models.DateTimeField()),
                ("registered_at", models.DateTimeField()),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.UUIDField(primary_key=True, serialize=False)),
                ("service_name", models.CharField()),
                ("display_name", models.CharField()),
                ("status", models.CharField()),
                ("port", models.IntegerField()),
                ("last_reported_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "server_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers.servers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Metrics",
            fields=[
                ("metric_id", models.UUIDField(primary_key=True, serialize=False)),
                ("metric_type", models.CharField()),
                ("value", models.FloatField()),
                ("unit", models.CharField()),
                ("labels", models.JSONField()),
                ("recorded_at", models.DateTimeField()),
                (
                    "server_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers.servers",
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers.service",
                    ),
                ),
            ],
        ),
    ]
