# Generated by Django 6.1.1 on 2026-09-03 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userpreference_default_environment_and_more'),
        ('servers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrics',
            options={'ordering': ['recorded_at', 'metric_id']},
        ),
        migrations.AlterModelOptions(
            name='servers',
            options={'ordering': ['name', 'server_id']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_name', 'service_id']},
        ),
        migrations.AddField(
            model_name='servers',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='labels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='metric_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='metric_type',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='recorded_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='servers.servers'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='servers.service'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='unit',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='servers',
            name='agent_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='servers',
            name='environment',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='servers',
            name='host_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servers',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servers',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servers',
            name='os_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='servers',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servers',
            name='server_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servers',
            name='status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('OFFLINE', 'Offline'), ('STALE', 'Stale'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=16),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_reported_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='servers.servers'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('OFFLINE', 'Offline'), ('STALE', 'Stale'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=16),
        ),
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['server_id', 'metric_type', 'recorded_at'], name='servers_met_server__43ca90_idx'),
        ),
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['service_id', 'metric_type', 'recorded_at'], name='servers_met_service_b3e30c_idx'),
        ),
        migrations.AddConstraint(
            model_name='servers',
            constraint=models.UniqueConstraint(fields=('organization', 'host_name'), name='unique_org_hostname'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('server_id', 'service_name'), name='unique_server_service_name'),
        ),
    ]
