# Generated by Django 6.1 on 2026-09-03 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0003_alter_servers_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connection_method",
                    models.CharField(default="REMOTE_WRITE", max_length=32),
                ),
                ("collector", models.CharField(blank=True, max_length=64)),
                ("collector_version", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONNECTED", "Connected"),
                            ("DEGRADED", "Degraded"),
                            ("DISCONNECTED", "Disconnected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "ingestion_health",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("HEALTHY", "Healthy"),
                            ("DEGRADED", "Degraded"),
                            ("STOPPED", "Stopped"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("last_callback_at", models.DateTimeField(blank=True, null=True)),
                ("last_metric_at", models.DateTimeField(blank=True, null=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disconnected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disconnected_monitoring_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_connection",
                        to="servers.servers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServerWriteCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secret_hash", models.CharField(editable=False, max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("GRACE", "Grace"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rotation_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="servers.monitoringconnection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_server_write_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("rotation_key__isnull", False)),
                        fields=("connection", "rotation_key"),
                        name="unique_connection_rotation_key",
                    )
                ],
            },
        ),
    ]
