# Generated by Django 6.1 on 2026-09-03 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0004_monitoringconnection_serverwritecredential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="serverwritecredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "ACTIVE")),
                fields=("connection",),
                name="unique_active_server_credential",
            ),
        ),
    ]
